# Generated by Django 3.1.2 on 2020-10-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('displayName', models.CharField(default='', max_length=100)),
                ('logo', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.CharField(blank=True, default='', max_length=20)),
                ('publisher', models.CharField(default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('detectionRules', models.JSONField(blank=True, default='')),
                ('returnCodes', models.JSONField(blank=True, default='')),
                ('installStr', models.CharField(max_length=255)),
                ('uninstallStr', models.CharField(max_length=255)),
            ],
        ),
    ]
