# Generated by Django 3.1.2 on 2020-10-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='detectionRules',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='software',
            name='returnCodes',
            field=models.JSONField(),
        ),
    ]
