# Generated by Django 3.1.2 on 2020-10-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0002_auto_20201028_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='detectionRules',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='returnCodes',
            field=models.JSONField(blank=True),
        ),
    ]
