# Generated by Django 3.1.2 on 2020-10-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0003_auto_20201028_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='displayName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='software',
            name='installStr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='software',
            name='publisher',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='software',
            name='uninstallStr',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
