# Generated by Django 3.1.2 on 2020-10-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0006_software_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='detectionRules',
            field=models.JSONField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='software',
            name='returnCodes',
            field=models.JSONField(blank=True, default='{}'),
        ),
    ]
