# Generated by Django 3.1.2 on 2020-10-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0007_auto_20201031_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='detectionRules',
            field=models.JSONField(blank=True, default='dict'),
        ),
        migrations.AlterField(
            model_name='software',
            name='parameters',
            field=models.JSONField(blank=True, default='dict'),
        ),
        migrations.AlterField(
            model_name='software',
            name='returnCodes',
            field=models.JSONField(blank=True, default='dict'),
        ),
    ]
